language: node_js
node_js: 12
deploy:
  provider: npm
  email: npm@t-code.pl
  api_key:
    secure: n7vx5qHF71MXgRttJCQzZU85ekxnfTUmW1et3I38LN67xutmLGJJgsbjeKdwcqVyKe6tL3lyHAd9+cHqWgpUKJnnH07yoQt1dluDJ/cGNihdLWKcwM8VATimMAFcc7i8gWbp0nbukDmC3guJ0COIu4DFtSo8pJ0rt7vLs4Uzxd6aQt/SdFJyKGKocyYvyfimtZdvBnJVsneqHY/a5cCi1PM+qSAwUMCPjKDnrrmX3s11QOBdtFN4VqsgQCana82eQ4TbU33mOSnJqqMRcGijvzgXGISJwXIRLl1NebS2FLfVlGW/srP3wvIkotmOc+iCGkRIPcAaYyZ6XLta8qYxT5FGWTCvrWzWVZ1kRZ2p6t8EvacXhE/YwBx3eE5oB9wVa904ctOfz4SFDtQ0aYKfmqWXsqZLRCiiZJYRdBttog/5nlKBOVyP9yJcUJfp/ClsAcUS9NMv3iQ0shpYSbQDfB0U0FVpsdGts2iS6+orwoj/90OEROpC5AcN9SyOuznvu60pXeYX/j4QfPT1lQegXd1l7MdLGsKFeR447jD425GeRVzSdszn7XRP1AFlj15rMRl6BAIEDjn0iKoHloUfAJeg83b403pxYzDL/MFTjfpT/Jcwu65wEzXySXkgGh26calKTDYscaVgjie/M1ZItessS1sBdqmYqhK6ynaPNHk=
  on:
    tags: true
    repo: tpluscode/eslint-config
